services:
    train:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
          - dogbreed:/app
        network_mode: "host"
        command: ["python3", "-m" ,"src.train"]
        shm_size: '2gb'

    evaluate:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
          - dogbreed:/app
        network_mode: "host"
        command: ["python3", "-m", "src.eval"]
        shm_size: '2gb'

    infer:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
          - dogbreed:/app
        network_mode: "host"
        command: ["python3","-m", "src.infer"]
        shm_size: '2gb'

volumes:
   dogbreed: