defaults:
  - data: dogbreed
  - loggers: tensorboard_logger
  - paths: default
  - trainer: default
  - hydra: default

task_name: "hydra_test"

test_model:
  _target_: src.model.timmclassifier.TimmClassifier.load_from_checkpoint
  checkpoint_path : "/Users/athvaithk/Documents/prep/EMLO/lightning_session4/logs/hydra_test/runs/2024-10-04_18-07-10/checkpoints/epoch_001.ckpt"
