defaults:
  - paths: default
  - hydra: default
  - data: catdog 

task_name: "hydra_test"
infer_n_images: 10
num_classes: 2
classes: ["Cat", "Dog"]

infer_model:
  _target_: src.model.timmclassifier.TimmClassifier.load_from_checkpoint
  checkpoint_path : "/Users/athvaithk/Documents/prep/EMLO/lightning_session4/logs/hydra_test/runs/2024-10-04_18-07-10/checkpoints/epoch_001.ckpt"
