defaults:
  - _self_
  - paths: default
  - data: catrabbit
  - model: timm_classifier
  - trainer: default
  - hydra: default
  - loggers: default
  - callbacks: default
  - experiment: null
  - hparam: null