defaults:
  - _self_
  - paths: default
  - data: dogbreed
  - model: timm_classifier
  - trainer: default
  - hydra: default
  - loggers: default
  - callbacks: default
  - experiment: dogbreed_ex

task_name: hydra_test

tags: ["run1"]

train: True

test: True