name: session_08_pipeline
on: 
  push:
    branches: [ session_08 ]
jobs:
  run_pipeline:
    name: Do the job on the runner
    runs-on: self-hosted # run the job on the newly created runner
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv sync
      
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      
      - name: Pull DVC data
        run: dvc pull -r session08_s3 data/CatRabbit
      
      - name: Run tests with coverage
        run: |
            uv run coverage run -m pytest
            uv run coverage xml -o coverage.xml
    
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
      
      - name: Train model
        run: |
          uv run dvc repro
      - name: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-region: ap-south-1
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: athvaith/session_08
          IMAGE_TAG: ${{ github.repository }}
          run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG